name: release

on:
  push:
    branches:
      - main
      - fix-release

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  id-token: write

jobs: 
  version:
    uses: hypha-rp/actions/.github/workflows/semantic-release.yml@main
    with:
      node-version: "22.x"
    secrets:
      github-token: ${{ secrets.PAT }}

  release:
    needs: version
    if: ${{ needs.version.outputs['semantic-release'].version != '' }}
    name: release ${{ needs.version.outputs['semantic-release'].version != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
