name: release

on:
  push:
    branches:
      - main
      - fix-release

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  id-token: write

jobs: 
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic-release.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        id: semantic-release
        uses: hypha-rp/actions/.github/actions/semantic-release@main
        with:
          node-version: '22'
          pat: ${{ secrets.PAT }}


  release:
    needs: version
    if: ${{ needs.version.outputs.version != '' }}
    name: release ${{ needs.version.outputs.version != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
