name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: semantic-release
        id: semantic
        uses: codfish/semantic-release-action@v3.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push new tag
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git fetch --tags
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}