name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  id-token: write

jobs: 
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic-release.outputs.version }}
      major-version: ${{ steps.semantic-release.outputs.major-version }}
      minor-version: ${{ steps.semantic-release.outputs.minor-version }}
    steps:
      - name: Semantic Release
        id: semantic-release
        uses: hypha-rp/actions/semantic-release@main
        with:
          node-version: '22'
          pat: ${{ secrets.PAT }}


  release:
    needs: version
    if: ${{ needs.version.outputs.version != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  container:
    needs: [version, release]
    if: ${{ needs.version.outputs.version != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build and push image
        uses: hypha-rp/actions/build-image@main
        with:
          tags: |
            ghcr.io/${{ github.repository }}:${{ needs.version.outputs.version }}
            ghcr.io/${{ github.repository }}:${{ needs.version.outputs.major-version }}
            ghcr.io/${{ github.repository }}:${{ needs.version.outputs.minor-version }}
            ghcr.io/${{ github.repository }}:latest
          push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}