name: update-submodules
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: ~

jobs:
  update-dev-tools:
    name: Update dev-tools submodule
    runs-on: ubuntu-latest
    steps:
      - name: Submodule Sync
        uses: mheap/submodule-sync-action@v1
        with:
          path: dev-tools
          ref: main
          pr_branch: automated-submodule-update
          target_branch: main